# Generated by cpp11: do not edit by hand

collectorGuess <- function(input, locale_, guessInteger) {
  .Call(`_meltr_collectorGuess`, input, locale_, guessInteger)
}

read_connection_ <- function(con, filename, chunk_size) {
  .Call(`_meltr_read_connection_`, con, filename, chunk_size)
}

read_file_ <- function(sourceSpec, locale_) {
  .Call(`_meltr_read_file_`, sourceSpec, locale_)
}

read_file_raw_ <- function(sourceSpec) {
  .Call(`_meltr_read_file_raw_`, sourceSpec)
}

read_lines_ <- function(sourceSpec, locale_, na, n_max, skip_empty_rows, progress) {
  .Call(`_meltr_read_lines_`, sourceSpec, locale_, na, n_max, skip_empty_rows, progress)
}

read_lines_chunked_ <- function(sourceSpec, locale_, na, chunkSize, callback, skip_empty_rows, progress) {
  invisible(.Call(`_meltr_read_lines_chunked_`, sourceSpec, locale_, na, chunkSize, callback, skip_empty_rows, progress))
}

read_lines_raw_ <- function(sourceSpec, n_max, progress) {
  .Call(`_meltr_read_lines_raw_`, sourceSpec, n_max, progress)
}

read_lines_raw_chunked_ <- function(sourceSpec, chunkSize, callback, progress) {
  invisible(.Call(`_meltr_read_lines_raw_chunked_`, sourceSpec, chunkSize, callback, progress))
}

read_tokens_ <- function(sourceSpec, tokenizerSpec, colSpecs, colNames, locale_, n_max, progress) {
  .Call(`_meltr_read_tokens_`, sourceSpec, tokenizerSpec, colSpecs, colNames, locale_, n_max, progress)
}

read_tokens_chunked_ <- function(sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, colNames, locale_, spec, progress) {
  invisible(.Call(`_meltr_read_tokens_chunked_`, sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, colNames, locale_, spec, progress))
}

melt_tokens_ <- function(sourceSpec, tokenizerSpec, colSpecs, locale_, n_max, progress) {
  .Call(`_meltr_melt_tokens_`, sourceSpec, tokenizerSpec, colSpecs, locale_, n_max, progress)
}

melt_tokens_chunked_ <- function(sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, locale_, progress) {
  invisible(.Call(`_meltr_melt_tokens_chunked_`, sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, locale_, progress))
}

guess_types_ <- function(sourceSpec, tokenizerSpec, locale_, n) {
  .Call(`_meltr_guess_types_`, sourceSpec, tokenizerSpec, locale_, n)
}

whitespaceColumns <- function(sourceSpec, n, comment) {
  .Call(`_meltr_whitespaceColumns`, sourceSpec, n, comment)
}
