# Generated by cpp11: do not edit by hand

collectorGuess <- function(input, locale_, guessInteger) {
  .Call(`_meltr_collectorGuess`, input, locale_, guessInteger)
}

read_connection_ <- function(con, filename, chunk_size) {
  .Call(`_meltr_read_connection_`, con, filename, chunk_size)
}

read_file_ <- function(sourceSpec, locale_) {
  .Call(`_meltr_read_file_`, sourceSpec, locale_)
}

read_file_raw_ <- function(sourceSpec) {
  .Call(`_meltr_read_file_raw_`, sourceSpec)
}

melt_tokens_ <- function(sourceSpec, tokenizerSpec, colSpecs, locale_, n_max, progress) {
  .Call(`_meltr_melt_tokens_`, sourceSpec, tokenizerSpec, colSpecs, locale_, n_max, progress)
}

melt_tokens_chunked_ <- function(sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, locale_, progress) {
  invisible(.Call(`_meltr_melt_tokens_chunked_`, sourceSpec, callback, chunkSize, tokenizerSpec, colSpecs, locale_, progress))
}

whitespaceColumns <- function(sourceSpec, n, comment) {
  .Call(`_meltr_whitespaceColumns`, sourceSpec, n, comment)
}
